version: '3'
services:

  rpi-simple-server:
    image: duckietown/rpi-simple-server:master18
    container_name: simple-server
    restart: always
    network_mode: "host"
    volumes:
      - /data:/data
      - /etc/avahi/services:/etc/avahi/services
    working_dir: /data

  rpi-health:
    image: duckietown/rpi-health:master18
    container_name: health
    restart: always
    network_mode: "host"
    devices:
      - /dev/vchiq:/dev/vchiq
    volumes:
      - /etc/avahi/services:/etc/avahi/services

  rpi-duckiebot-online:
    image: duckietown/rpi-duckiebot-online:master18
    container_name: duckiebot-online
    restart: always
    network_mode: "host"
    volumes:
      - /data:/data
      - /secrets:/secrets
      - /var/local:/var/local
      - /etc/avahi/services:/etc/avahi/services

  rpi-duckiebot-loader:
    image: duckietown/rpi-duckiebot-loader:master18
    container_name: duckiebot-loader
    restart: always
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data:/data
      - /secrets:/secrets
      - /var/local:/var/local
      - /etc/avahi/services:/etc/avahi/services
