version: '3'
services:

  duckiebot-interface:
    image: duckietown/dt-duckiebot-interface:daffy
    container_name: duckiebot-interface
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      DISABLE_CONTRACTS: 1
    volumes:
      - /data:/data
      - /etc/avahi/services:/etc/avahi/services

  car-interface:
    image: duckietown/dt-car-interface:daffy
    container_name: car-interface
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      DISABLE_CONTRACTS: 1
    volumes:
      - /data:/data
      - /etc/avahi/services:/etc/avahi/services
