version: '3'
services:

  rpi-python-picamera:
    image: duckietown/rpi-python-picamera:master18
    container_name: python-picamera
    network_mode: host
    volumes:
      # avahi services
      - /etc/avahi/services:/etc/avahi/services

  rpi-simple-server:
    image: duckietown/rpi-simple-server:master18
    container_name: simple-server
    restart: always
    network_mode: "host"
    volumes:
      - /data:/data
      # avahi services
      - /etc/avahi/services:/etc/avahi/services
    working_dir: /data
